spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/joybox
    username: postgres
    password: 1234

jwt:
  private-key:
    MIIEpAIBAAKCAQEArIL5pgvpbUfUBBJFoa0BgoVXL81vpIodEKcqVzSpNgHBrtjzUL0d7yC6s3mnkvBmNQjypx+PL68Fdk9Dj5qlXwqeqPvZTve/Gen/kEe9qA7Oa16wmKRi04SkVVAwOlDBeO6oBBywyQasZKJLe/4Tms9+RR78UEieJKrBBSwrsX2Va4iA8Wvjre6lMca/GF1qliBAT6krxBg/2/IzC88kXWCEBw5KlUkLlixgntiORqkY2vt8p2Ft0QX02/Ch+x+dBEAfzPuF3V3B6M/EhHGRMK4eqqZT8bOOuxsA6rdFL9f71o7suaMe1H3fOXfQldxUSQtT/zOt0fOaxfdhbIy0YwIDAQABAoIBAQCOrWjCz1lJO737fA1BEXCNPbEFZTiv8lblngxjwbctZriE3wQmQ7ONQhmINNbGrbMqq/LdDDoFqxCucBIlpDaf642bn2h0am0QhrsK3nrakxxgKxmNtW/TFwI/WSn6IS5S0bf+ZqhEKxPLy3r42wPl5zS9AEqYL+cz1lH78DNXAHW/INQzGNxHYIQ6EDcB4779oyboGB8ozNxzxXxhscJhP6JjpfAPLg3iBtFzF1tXtu4bLPeGFY1ulL6zjFZJxDh1kqHq1BIsLqA/6rX+X8EE26RULeKnDYiELl+TdaFdvt4pq8Uq1M4PM+o6lkkxEC1lNh8yJ4kSNeuEfZwUj7XBAoGBAN3/56C2xzfTIJqH2hYWRsGvqdVLxr6k2awuNhHlRjoTcymvjZx/ahZ04I8S27lxR0+qRTZmltVEoF+VfgfWV9euwvij5t0V7XBx/xHPWo6kfVRGciZYLkXhBm6pyD07ma5w/J8Das+dPlKz8dinTF9BW2KIrXRjL9hxffR/tMqhAoGBAMbuwmhU6rwqsfOCSrMAYnp56KZ7KwbcPnsxE6Gr67Sd4gT6K5GHmsfr18NZlu0ax73pSmmMN5TBVzR7HkO41FLOpuR0n/pZOpP65zVPzBUoc8HF11H+zKpDym5XQh+WDApuhZl4akPVWHhWf7O+ltdSE5sRnnYuUJrDemGtzoSDAoGBAJTI1OGGfoAwlNJcqFJTPbrD04wrjBjrfSODmSNnSSjVLkLK8JrpXh2M2Y+qMO7ZN9Txpg9utDpdEyrckyoHgrn/25YuqySTdJ3/GNdD5EpjfcfEqu59/Q1CYkA6tAQt9LLP8M9Vx/k7RrDA/x6YCXxx3iBsv+uYKlHixmreSDnhAoGAUt7Bg77kLlDG4r8DKUBexdClFz019lyndqBCIlZBEXO35QTmQ3CvDNt1fX6DvfArBzT497Eeskw8bLNhLyr+4CQQKBlhT2P+YAjkajP8u0+nsTAee5zeW4tz97VH6WqTR4E1DHK6KdnlSfQWrKUXp0kcu7uCPI8cquwFvk0uO8sCgYB0BmcmhIVkS+Y8hzaH7sJ4xgGOTQeJ/C4zDdubPqUoBD5+YAGpLTENa8tK5vorE9ANuPQF1HhEwWg3hgU7vM53gCSHa2OrB4wopb/pMzWkduq+ZYRuQMOQUHUEcqNi1DuqVN/SLRC2q31088edUW0OilGN/vUEzAJVWrKLkEclhA==
  public-key:
    MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEArIL5pgvpbUfUBBJFoa0BgoVXL81vpIodEKcqVzSpNgHBrtjzUL0d7yC6s3mnkvBmNQjypx+PL68Fdk9Dj5qlXwqeqPvZTve/Gen/kEe9qA7Oa16wmKRi04SkVVAwOlDBeO6oBBywyQasZKJLe/4Tms9+RR78UEieJKrBBSwrsX2Va4iA8Wvjre6lMca/GF1qliBAT6krxBg/2/IzC88kXWCEBw5KlUkLlixgntiORqkY2vt8p2Ft0QX02/Ch+x+dBEAfzPuF3V3B6M/EhHGRMK4eqqZT8bOOuxsA6rdFL9f71o7suaMe1H3fOXfQldxUSQtT/zOt0fOaxfdhbIy0YwIDAQAB

cloud:
  aws:
    endpoint: http://127.0.0.1:4566
    accessKey: access-key
    secretKey: secret-key
    region: region
    bucket: vendor-logo
