product:
  db:
    url: <helm-secret>
    username: <helm-secret>
    password: <helm-secret>

jwt:
  key:
    private: <helm-secret>
    public: <helm-secret>

spring:
  datasource:
    url: jdbc:postgresql://${product.db.url}
    username: ${product.db.username}
    password: ${product.db.password}

  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect

  flyway:
    enabled: true
    baseline-on-migrate: true
    url: ${spring.datasource.url}
    user: ${spring.datasource.username}
    password: ${spring.datasource.password}

cloud:
  aws:
    bucket: joybox-user-vendor-logo

springdoc:
  api-docs:
    enabled: false
  swagger-ui:
    url: /openapi.yaml
    path: /api-docs

server:
  port: 80
#  tomcat:
#    accesslog:
#      enabled: true
#      directory: logs
#      suffix: .log
#      prefix: access_log
#      file-date-format: .yyyy-MM-dd
#      pattern: %{yyyy-MM-dd HH:mm:ss}t %s %r %{User-Agent}i %{Referer}i %a %b
#    basedir: .


management:
  endpoints:
    web:
      base-path: /